"""Describe your migration here

Revision ID: 528bd5c572ab
Revises: a3194d2cdbb5
Create Date: 2024-10-16 23:46:44.856928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528bd5c572ab'
down_revision = 'a3194d2cdbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mbti_analyses', schema=None) as batch_op:
        batch_op.alter_column('mbti_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mbti_analyses', schema=None) as batch_op:
        batch_op.alter_column('mbti_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###
