"""Add UserMBTIProfile model

Revision ID: 607eee611fdd
Revises: cec7b69007b5
Create Date: 2024-10-16 12:45:06.919717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607eee611fdd'
down_revision = 'cec7b69007b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mbti_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mbti_type', sa.String(length=4), nullable=True),
    sa.Column('dominant_function', sa.String(length=10), nullable=True),
    sa.Column('auxiliary_function', sa.String(length=10), nullable=True),
    sa.Column('tertiary_function', sa.String(length=10), nullable=True),
    sa.Column('inferior_function', sa.String(length=10), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_mbti_profiles')
    # ### end Alembic commands ###
