"""Describe your migration here

Revision ID: 9b3e2d93189e
Revises: 528bd5c572ab
Create Date: 2024-10-16 23:52:07.512898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3e2d93189e'
down_revision = '528bd5c572ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mbti_analyses', schema=None) as batch_op:
        batch_op.alter_column('mbti_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mbti_analyses', schema=None) as batch_op:
        batch_op.alter_column('mbti_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
