"""Add mbti_type to User model

Revision ID: c0de74d118c2
Revises: 0dbe15addf02
Create Date: 2024-10-15 02:59:22.221203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0de74d118c2'
down_revision = '0dbe15addf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbti_type', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mbti_type')

    # ### end Alembic commands ###
